
-- --------------------------------------------------
-- Entity Designer DDL Script for SQL Server 2005, 2008, 2012 and Azure
-- --------------------------------------------------
-- Date Created: 11/05/2017 23:02:53
-- Generated from EDMX file: D:\Programacion\OpoV2.0.0\Oporie\Oporie.Infraestructura.Data.ModuloPrincipal\ModuloPrincipalDataModel.edmx
-- --------------------------------------------------

SET QUOTED_IDENTIFIER OFF;
GO
USE [Oporie];
GO
IF SCHEMA_ID(N'dbo') IS NULL EXECUTE(N'CREATE SCHEMA [dbo]');
GO

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

IF OBJECT_ID(N'[COL].[FK_ALUMNO_AREA_GEOGRAFICA]', 'F') IS NOT NULL
    ALTER TABLE [COL].[ALUMNO] DROP CONSTRAINT [FK_ALUMNO_AREA_GEOGRAFICA];
GO
IF OBJECT_ID(N'[COL].[FK_ALUMNO_TELEFONO]', 'F') IS NOT NULL
    ALTER TABLE [COL].[ALUMNO] DROP CONSTRAINT [FK_ALUMNO_TELEFONO];
GO
IF OBJECT_ID(N'[CTL].[FK_AREA_GEOGRAFICA_AREA_GEOGRAFICA]', 'F') IS NOT NULL
    ALTER TABLE [CTL].[AREA_GEOGRAFICA] DROP CONSTRAINT [FK_AREA_GEOGRAFICA_AREA_GEOGRAFICA];
GO
IF OBJECT_ID(N'[CTL].[FK_AREA_GEOGRAFICA_CODIGOS]', 'F') IS NOT NULL
    ALTER TABLE [CTL].[AREA_GEOGRAFICA] DROP CONSTRAINT [FK_AREA_GEOGRAFICA_CODIGOS];
GO
IF OBJECT_ID(N'[CTL].[FK_CARGO_CARGO]', 'F') IS NOT NULL
    ALTER TABLE [CTL].[CARGO] DROP CONSTRAINT [FK_CARGO_CARGO];
GO
IF OBJECT_ID(N'[EDU].[FK_COLEGIATURA_HORARIO]', 'F') IS NOT NULL
    ALTER TABLE [EDU].[COLEGIATURA] DROP CONSTRAINT [FK_COLEGIATURA_HORARIO];
GO
IF OBJECT_ID(N'[EDU].[FK_COLEGIATURA_PERIODO]', 'F') IS NOT NULL
    ALTER TABLE [EDU].[COLEGIATURA] DROP CONSTRAINT [FK_COLEGIATURA_PERIODO];
GO
IF OBJECT_ID(N'[COL].[FK_ENTORNO_FAMILIAR_REPRESENTANTE]', 'F') IS NOT NULL
    ALTER TABLE [COL].[ENTORNO_FAMILIAR] DROP CONSTRAINT [FK_ENTORNO_FAMILIAR_REPRESENTANTE];
GO
IF OBJECT_ID(N'[EDU].[FK_INSCRIPCION_ALUMNO]', 'F') IS NOT NULL
    ALTER TABLE [EDU].[INSCRIPCION] DROP CONSTRAINT [FK_INSCRIPCION_ALUMNO];
GO
IF OBJECT_ID(N'[EDU].[FK_MATRICULA_HORARIO]', 'F') IS NOT NULL
    ALTER TABLE [EDU].[MATRICULA] DROP CONSTRAINT [FK_MATRICULA_HORARIO];
GO
IF OBJECT_ID(N'[EDU].[FK_MATRICULA_INSCRIPCION]', 'F') IS NOT NULL
    ALTER TABLE [EDU].[MATRICULA] DROP CONSTRAINT [FK_MATRICULA_INSCRIPCION];
GO
IF OBJECT_ID(N'[EDU].[FK_MATRICULA_PERIODO]', 'F') IS NOT NULL
    ALTER TABLE [EDU].[MATRICULA] DROP CONSTRAINT [FK_MATRICULA_PERIODO];
GO
IF OBJECT_ID(N'[COL].[FK_PERSONA_CARGO]', 'F') IS NOT NULL
    ALTER TABLE [COL].[PERSONA] DROP CONSTRAINT [FK_PERSONA_CARGO];
GO
IF OBJECT_ID(N'[COL].[FK_PERSONA_TELEFONO]', 'F') IS NOT NULL
    ALTER TABLE [COL].[PERSONA] DROP CONSTRAINT [FK_PERSONA_TELEFONO];
GO
IF OBJECT_ID(N'[CTL].[FK_REFERENCIA_TELEFONO]', 'F') IS NOT NULL
    ALTER TABLE [CTL].[REFERENCIA] DROP CONSTRAINT [FK_REFERENCIA_TELEFONO];
GO
IF OBJECT_ID(N'[COL].[FK_REPRESENTANTE_ALUMNO]', 'F') IS NOT NULL
    ALTER TABLE [COL].[REPRESENTANTE] DROP CONSTRAINT [FK_REPRESENTANTE_ALUMNO];
GO
IF OBJECT_ID(N'[COL].[FK_REPRESENTANTE_LEGAL_MATRICULA]', 'F') IS NOT NULL
    ALTER TABLE [COL].[REPRESENTANTE_LEGAL] DROP CONSTRAINT [FK_REPRESENTANTE_LEGAL_MATRICULA];
GO
IF OBJECT_ID(N'[COL].[FK_REPRESENTANTE_LEGAL_TELEFONO]', 'F') IS NOT NULL
    ALTER TABLE [COL].[REPRESENTANTE_LEGAL] DROP CONSTRAINT [FK_REPRESENTANTE_LEGAL_TELEFONO];
GO
IF OBJECT_ID(N'[COL].[FK_REPRESENTANTE_PARENTESCO]', 'F') IS NOT NULL
    ALTER TABLE [COL].[REPRESENTANTE] DROP CONSTRAINT [FK_REPRESENTANTE_PARENTESCO];
GO
IF OBJECT_ID(N'[COL].[FK_REPRESENTANTE_PERSONA]', 'F') IS NOT NULL
    ALTER TABLE [COL].[REPRESENTANTE] DROP CONSTRAINT [FK_REPRESENTANTE_PERSONA];
GO
IF OBJECT_ID(N'[EDU].[FK_REQUISITOS_MATRICULA_MATRICULA]', 'F') IS NOT NULL
    ALTER TABLE [EDU].[REQUISITOS_MATRICULA] DROP CONSTRAINT [FK_REQUISITOS_MATRICULA_MATRICULA];
GO
IF OBJECT_ID(N'[EDU].[FK_REQUISITOS_MATRICULA_REQUISITO]', 'F') IS NOT NULL
    ALTER TABLE [EDU].[REQUISITOS_MATRICULA] DROP CONSTRAINT [FK_REQUISITOS_MATRICULA_REQUISITO];
GO

-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

IF OBJECT_ID(N'[COL].[ALUMNO]', 'U') IS NOT NULL
    DROP TABLE [COL].[ALUMNO];
GO
IF OBJECT_ID(N'[COL].[ENTORNO_FAMILIAR]', 'U') IS NOT NULL
    DROP TABLE [COL].[ENTORNO_FAMILIAR];
GO
IF OBJECT_ID(N'[COL].[PERSONA]', 'U') IS NOT NULL
    DROP TABLE [COL].[PERSONA];
GO
IF OBJECT_ID(N'[COL].[REPRESENTANTE]', 'U') IS NOT NULL
    DROP TABLE [COL].[REPRESENTANTE];
GO
IF OBJECT_ID(N'[COL].[REPRESENTANTE_LEGAL]', 'U') IS NOT NULL
    DROP TABLE [COL].[REPRESENTANTE_LEGAL];
GO
IF OBJECT_ID(N'[CTL].[AREA_GEOGRAFICA]', 'U') IS NOT NULL
    DROP TABLE [CTL].[AREA_GEOGRAFICA];
GO
IF OBJECT_ID(N'[CTL].[CARGO]', 'U') IS NOT NULL
    DROP TABLE [CTL].[CARGO];
GO
IF OBJECT_ID(N'[CTL].[CODIGOS]', 'U') IS NOT NULL
    DROP TABLE [CTL].[CODIGOS];
GO
IF OBJECT_ID(N'[CTL].[HORARIO]', 'U') IS NOT NULL
    DROP TABLE [CTL].[HORARIO];
GO
IF OBJECT_ID(N'[CTL].[PARENTESCO]', 'U') IS NOT NULL
    DROP TABLE [CTL].[PARENTESCO];
GO
IF OBJECT_ID(N'[CTL].[PERIODO]', 'U') IS NOT NULL
    DROP TABLE [CTL].[PERIODO];
GO
IF OBJECT_ID(N'[CTL].[REFERENCIA]', 'U') IS NOT NULL
    DROP TABLE [CTL].[REFERENCIA];
GO
IF OBJECT_ID(N'[CTL].[REQUISITO]', 'U') IS NOT NULL
    DROP TABLE [CTL].[REQUISITO];
GO
IF OBJECT_ID(N'[CTL].[TELEFONO]', 'U') IS NOT NULL
    DROP TABLE [CTL].[TELEFONO];
GO
IF OBJECT_ID(N'[EDU].[COLEGIATURA]', 'U') IS NOT NULL
    DROP TABLE [EDU].[COLEGIATURA];
GO
IF OBJECT_ID(N'[EDU].[INSCRIPCION]', 'U') IS NOT NULL
    DROP TABLE [EDU].[INSCRIPCION];
GO
IF OBJECT_ID(N'[EDU].[MATRICULA]', 'U') IS NOT NULL
    DROP TABLE [EDU].[MATRICULA];
GO
IF OBJECT_ID(N'[EDU].[REQUISITOS_MATRICULA]', 'U') IS NOT NULL
    DROP TABLE [EDU].[REQUISITOS_MATRICULA];
GO

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'ALUMNO'
CREATE TABLE [dbo].[ALUMNO] (
    [ID_ALUMNO] uniqueidentifier  NOT NULL,
    [ID_AREAGEOGRAFICA] uniqueidentifier  NOT NULL,
    [ID_TELEFONO] uniqueidentifier  NULL,
    [ALU_ID_INGRESADOPOR] uniqueidentifier  NULL,
    [ALU_CEDULA] varchar(10)  NULL,
    [ALU_FIRSTNAME] varchar(50)  NOT NULL,
    [ALU_LASTNAME] varchar(50)  NOT NULL,
    [ALU_GENERO] char(1)  NULL,
    [ALU_FECHANAC] datetime  NULL,
    [ALU_FOTO] varbinary(max)  NULL,
    [ALU_LUGARNAC] varchar(120)  NULL,
    [ALU_DIRECCION] varchar(250)  NULL,
    [ALU_FECHAINGRESO] datetime  NULL,
    [ALU_ESTADOCIVIL] char(50)  NULL,
    [ALU_EMAIL] varchar(200)  NULL,
    [ALU_ESTADO] bit  NOT NULL
);
GO

-- Creating table 'ENTORNO_FAMILIAR'
CREATE TABLE [dbo].[ENTORNO_FAMILIAR] (
    [ID_ENTORNOFAMILIAR] uniqueidentifier  NOT NULL,
    [ID_STATUSVIVIENDA] uniqueidentifier  NULL,
    [ID_TIPOVIVIENDA] uniqueidentifier  NULL,
    [ID_SECTOR] uniqueidentifier  NULL,
    [ID_REPRESENTANTE] uniqueidentifier  NULL,
    [EFA_DIRECCIONTRABAJO] varchar(250)  NULL,
    [EFA_INSTRUCCION] varchar(250)  NULL,
    [EFA_PROFESION] varchar(250)  NULL,
    [EFA_OCUPACION] varchar(250)  NULL,
    [EFA_OTRASACTIVIDADES] varchar(250)  NULL,
    [EFA_TIEMPOLIBRE] varchar(250)  NULL,
    [EFA_NUMEROEMBARAZOS] smallint  NULL,
    [EFA_NUMEROPARTOS] smallint  NULL,
    [EFA_OBSERVACIONES] varchar(250)  NULL,
    [EFA_ESTADO] bit  NOT NULL
);
GO

-- Creating table 'PERSONA'
CREATE TABLE [dbo].[PERSONA] (
    [ID_PERSONA] uniqueidentifier  NOT NULL,
    [ID_AREAGEOGRAFICA] uniqueidentifier  NOT NULL,
    [ID_TELEFONO] uniqueidentifier  NULL,
    [ID_CARGO] uniqueidentifier  NULL,
    [PER_CEDULA] varchar(10)  NULL,
    [PER_FIRSTNAME] varchar(50)  NOT NULL,
    [PER_LASTNAME] varchar(50)  NOT NULL,
    [PER_GENERO] char(1)  NULL,
    [PER_FECHANAC] datetime  NULL,
    [PER_FOTO] varbinary(max)  NULL,
    [PER_LUGARNAC] varchar(120)  NULL,
    [PER_DIRECCION] varchar(250)  NULL,
    [PER_ESTADOCIVIL] char(50)  NULL,
    [PER_EMAIL] varchar(200)  NULL,
    [PER_ESTADO] bit  NOT NULL
);
GO

-- Creating table 'REPRESENTANTE'
CREATE TABLE [dbo].[REPRESENTANTE] (
    [ID_REPRESENTANTE] uniqueidentifier  NOT NULL,
    [ID_PARENTESCO] uniqueidentifier  NOT NULL,
    [ID_PERSONA] uniqueidentifier  NOT NULL,
    [ID_ALUMNO] uniqueidentifier  NOT NULL,
    [REP_FECHAINGRESO] datetime  NULL,
    [REP_ESTADO] bit  NOT NULL
);
GO

-- Creating table 'REPRESENTANTE_LEGAL'
CREATE TABLE [dbo].[REPRESENTANTE_LEGAL] (
    [ID_REPRESENTANTELEGAL] uniqueidentifier  NOT NULL,
    [ID_MATRICULA] uniqueidentifier  NOT NULL,
    [ID_TELEFONO] uniqueidentifier  NULL,
    [RLE_CEDULA] varchar(10)  NULL,
    [RLE_FIRSTNAME] varchar(50)  NOT NULL,
    [RLE_LASTNAME] varchar(50)  NOT NULL,
    [RLE_DIRECCION] varchar(250)  NULL,
    [RLE_ESTADO] bit  NOT NULL
);
GO

-- Creating table 'AREA_GEOGRAFICA'
CREATE TABLE [dbo].[AREA_GEOGRAFICA] (
    [ID_AREAGEOGRAFICA] uniqueidentifier  NOT NULL,
    [ID_AREAGEOPADRE] uniqueidentifier  NULL,
    [ID_CODIGO] varchar(100)  NULL,
    [AG_DESCRIPCION] varchar(100)  NOT NULL,
    [AG_ESTADO] bit  NOT NULL
);
GO

-- Creating table 'CARGO'
CREATE TABLE [dbo].[CARGO] (
    [ID_CARGO] uniqueidentifier  NOT NULL,
    [ID_CARGOPADRE] uniqueidentifier  NULL,
    [CAR_CODIGO] varchar(50)  NOT NULL,
    [CAR_DESCRIPCION] varchar(250)  NOT NULL,
    [CAR_ESTADO] bit  NOT NULL
);
GO

-- Creating table 'CODIGOS'
CREATE TABLE [dbo].[CODIGOS] (
    [ID_CODIGO] varchar(100)  NOT NULL,
    [COD_DESCRIPCION] varchar(250)  NOT NULL,
    [COD_ESTADO] bit  NOT NULL
);
GO

-- Creating table 'HORARIO'
CREATE TABLE [dbo].[HORARIO] (
    [ID_HORARIO] uniqueidentifier  NOT NULL,
    [HOR_DESCRIPCION] varchar(250)  NOT NULL,
    [HOR_ESTADO] bit  NOT NULL
);
GO

-- Creating table 'PARENTESCO'
CREATE TABLE [dbo].[PARENTESCO] (
    [ID_PARENTESCO] uniqueidentifier  NOT NULL,
    [PAR_DESCRIPCION] varchar(250)  NOT NULL,
    [PAR_ESTADO] bit  NOT NULL
);
GO

-- Creating table 'PERIODO'
CREATE TABLE [dbo].[PERIODO] (
    [ID_PERIODO] uniqueidentifier  NOT NULL,
    [PER_FECHAINICIO] datetime  NOT NULL,
    [PER_FECHAFIN] datetime  NOT NULL,
    [PER_ESTADO] bit  NOT NULL
);
GO

-- Creating table 'REFERENCIA'
CREATE TABLE [dbo].[REFERENCIA] (
    [ID_REFERENCIA] uniqueidentifier  NOT NULL,
    [ID_TELEFONO] uniqueidentifier  NOT NULL,
    [REF_CEDULA] varchar(10)  NULL,
    [REF_FIRSTNAME] varchar(50)  NOT NULL,
    [REF_LASTNAME] varchar(50)  NULL,
    [REF_DIRECCION] varchar(250)  NULL,
    [REF_ESTADO] bit  NOT NULL
);
GO

-- Creating table 'REQUISITO'
CREATE TABLE [dbo].[REQUISITO] (
    [ID_REQUISITO] uniqueidentifier  NOT NULL,
    [REQ_DESCRIPCION] varchar(250)  NOT NULL,
    [REQ_ESTADO] bit  NOT NULL
);
GO

-- Creating table 'TELEFONO'
CREATE TABLE [dbo].[TELEFONO] (
    [ID_TELEFONO] uniqueidentifier  NOT NULL,
    [TEL_NUMERO] varchar(50)  NOT NULL,
    [TEL_ESTADO] bit  NOT NULL
);
GO

-- Creating table 'COLEGIATURA'
CREATE TABLE [dbo].[COLEGIATURA] (
    [ID_COLEGIATURA] uniqueidentifier  NOT NULL,
    [ID_PERIODO] uniqueidentifier  NOT NULL,
    [ID_HORARIO] uniqueidentifier  NOT NULL,
    [COL_VALOR] float  NOT NULL,
    [COL_DESCRIPCION] varchar(250)  NOT NULL,
    [COL_FECHAPAGO] datetime  NULL,
    [COL_ESTADO] bit  NOT NULL
);
GO

-- Creating table 'INSCRIPCION'
CREATE TABLE [dbo].[INSCRIPCION] (
    [ID_INSCRIPCION] uniqueidentifier  NOT NULL,
    [ID_ALUMNO] uniqueidentifier  NOT NULL,
    [INS_FECHAINGRESO] datetime  NULL,
    [INS_OBSERVACION] varchar(250)  NULL,
    [INS_ESTADO] bit  NOT NULL
);
GO

-- Creating table 'MATRICULA'
CREATE TABLE [dbo].[MATRICULA] (
    [ID_MATRICULA] uniqueidentifier  NOT NULL,
    [ID_INSCRIPCION] uniqueidentifier  NOT NULL,
    [ID_PERIODO] uniqueidentifier  NOT NULL,
    [ID_HORARIO] uniqueidentifier  NOT NULL,
    [MAT_FECHAINGRESO] datetime  NULL,
    [MAT_ESTADO] bit  NOT NULL
);
GO

-- Creating table 'REQUISITOS_MATRICULA'
CREATE TABLE [dbo].[REQUISITOS_MATRICULA] (
    [ID_REQUISITOMATRICULA] uniqueidentifier  NOT NULL,
    [ID_REQUISITO] uniqueidentifier  NOT NULL,
    [ID_MATRICULA] uniqueidentifier  NOT NULL,
    [RMA_ESTADO] bit  NOT NULL
);
GO

-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on [ID_ALUMNO] in table 'ALUMNO'
ALTER TABLE [dbo].[ALUMNO]
ADD CONSTRAINT [PK_ALUMNO]
    PRIMARY KEY CLUSTERED ([ID_ALUMNO] ASC);
GO

-- Creating primary key on [ID_ENTORNOFAMILIAR] in table 'ENTORNO_FAMILIAR'
ALTER TABLE [dbo].[ENTORNO_FAMILIAR]
ADD CONSTRAINT [PK_ENTORNO_FAMILIAR]
    PRIMARY KEY CLUSTERED ([ID_ENTORNOFAMILIAR] ASC);
GO

-- Creating primary key on [ID_PERSONA] in table 'PERSONA'
ALTER TABLE [dbo].[PERSONA]
ADD CONSTRAINT [PK_PERSONA]
    PRIMARY KEY CLUSTERED ([ID_PERSONA] ASC);
GO

-- Creating primary key on [ID_REPRESENTANTE] in table 'REPRESENTANTE'
ALTER TABLE [dbo].[REPRESENTANTE]
ADD CONSTRAINT [PK_REPRESENTANTE]
    PRIMARY KEY CLUSTERED ([ID_REPRESENTANTE] ASC);
GO

-- Creating primary key on [ID_REPRESENTANTELEGAL] in table 'REPRESENTANTE_LEGAL'
ALTER TABLE [dbo].[REPRESENTANTE_LEGAL]
ADD CONSTRAINT [PK_REPRESENTANTE_LEGAL]
    PRIMARY KEY CLUSTERED ([ID_REPRESENTANTELEGAL] ASC);
GO

-- Creating primary key on [ID_AREAGEOGRAFICA] in table 'AREA_GEOGRAFICA'
ALTER TABLE [dbo].[AREA_GEOGRAFICA]
ADD CONSTRAINT [PK_AREA_GEOGRAFICA]
    PRIMARY KEY CLUSTERED ([ID_AREAGEOGRAFICA] ASC);
GO

-- Creating primary key on [ID_CARGO] in table 'CARGO'
ALTER TABLE [dbo].[CARGO]
ADD CONSTRAINT [PK_CARGO]
    PRIMARY KEY CLUSTERED ([ID_CARGO] ASC);
GO

-- Creating primary key on [ID_CODIGO] in table 'CODIGOS'
ALTER TABLE [dbo].[CODIGOS]
ADD CONSTRAINT [PK_CODIGOS]
    PRIMARY KEY CLUSTERED ([ID_CODIGO] ASC);
GO

-- Creating primary key on [ID_HORARIO] in table 'HORARIO'
ALTER TABLE [dbo].[HORARIO]
ADD CONSTRAINT [PK_HORARIO]
    PRIMARY KEY CLUSTERED ([ID_HORARIO] ASC);
GO

-- Creating primary key on [ID_PARENTESCO] in table 'PARENTESCO'
ALTER TABLE [dbo].[PARENTESCO]
ADD CONSTRAINT [PK_PARENTESCO]
    PRIMARY KEY CLUSTERED ([ID_PARENTESCO] ASC);
GO

-- Creating primary key on [ID_PERIODO] in table 'PERIODO'
ALTER TABLE [dbo].[PERIODO]
ADD CONSTRAINT [PK_PERIODO]
    PRIMARY KEY CLUSTERED ([ID_PERIODO] ASC);
GO

-- Creating primary key on [ID_REFERENCIA] in table 'REFERENCIA'
ALTER TABLE [dbo].[REFERENCIA]
ADD CONSTRAINT [PK_REFERENCIA]
    PRIMARY KEY CLUSTERED ([ID_REFERENCIA] ASC);
GO

-- Creating primary key on [ID_REQUISITO] in table 'REQUISITO'
ALTER TABLE [dbo].[REQUISITO]
ADD CONSTRAINT [PK_REQUISITO]
    PRIMARY KEY CLUSTERED ([ID_REQUISITO] ASC);
GO

-- Creating primary key on [ID_TELEFONO] in table 'TELEFONO'
ALTER TABLE [dbo].[TELEFONO]
ADD CONSTRAINT [PK_TELEFONO]
    PRIMARY KEY CLUSTERED ([ID_TELEFONO] ASC);
GO

-- Creating primary key on [ID_COLEGIATURA] in table 'COLEGIATURA'
ALTER TABLE [dbo].[COLEGIATURA]
ADD CONSTRAINT [PK_COLEGIATURA]
    PRIMARY KEY CLUSTERED ([ID_COLEGIATURA] ASC);
GO

-- Creating primary key on [ID_INSCRIPCION] in table 'INSCRIPCION'
ALTER TABLE [dbo].[INSCRIPCION]
ADD CONSTRAINT [PK_INSCRIPCION]
    PRIMARY KEY CLUSTERED ([ID_INSCRIPCION] ASC);
GO

-- Creating primary key on [ID_MATRICULA] in table 'MATRICULA'
ALTER TABLE [dbo].[MATRICULA]
ADD CONSTRAINT [PK_MATRICULA]
    PRIMARY KEY CLUSTERED ([ID_MATRICULA] ASC);
GO

-- Creating primary key on [ID_REQUISITOMATRICULA] in table 'REQUISITOS_MATRICULA'
ALTER TABLE [dbo].[REQUISITOS_MATRICULA]
ADD CONSTRAINT [PK_REQUISITOS_MATRICULA]
    PRIMARY KEY CLUSTERED ([ID_REQUISITOMATRICULA] ASC);
GO

-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on [ID_AREAGEOGRAFICA] in table 'ALUMNO'
ALTER TABLE [dbo].[ALUMNO]
ADD CONSTRAINT [FK_ALUMNO_AREA_GEOGRAFICA]
    FOREIGN KEY ([ID_AREAGEOGRAFICA])
    REFERENCES [dbo].[AREA_GEOGRAFICA]
        ([ID_AREAGEOGRAFICA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ALUMNO_AREA_GEOGRAFICA'
CREATE INDEX [IX_FK_ALUMNO_AREA_GEOGRAFICA]
ON [dbo].[ALUMNO]
    ([ID_AREAGEOGRAFICA]);
GO

-- Creating foreign key on [ID_TELEFONO] in table 'ALUMNO'
ALTER TABLE [dbo].[ALUMNO]
ADD CONSTRAINT [FK_ALUMNO_TELEFONO]
    FOREIGN KEY ([ID_TELEFONO])
    REFERENCES [dbo].[TELEFONO]
        ([ID_TELEFONO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ALUMNO_TELEFONO'
CREATE INDEX [IX_FK_ALUMNO_TELEFONO]
ON [dbo].[ALUMNO]
    ([ID_TELEFONO]);
GO

-- Creating foreign key on [ID_ALUMNO] in table 'INSCRIPCION'
ALTER TABLE [dbo].[INSCRIPCION]
ADD CONSTRAINT [FK_INSCRIPCION_ALUMNO]
    FOREIGN KEY ([ID_ALUMNO])
    REFERENCES [dbo].[ALUMNO]
        ([ID_ALUMNO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_INSCRIPCION_ALUMNO'
CREATE INDEX [IX_FK_INSCRIPCION_ALUMNO]
ON [dbo].[INSCRIPCION]
    ([ID_ALUMNO]);
GO

-- Creating foreign key on [ID_ALUMNO] in table 'REPRESENTANTE'
ALTER TABLE [dbo].[REPRESENTANTE]
ADD CONSTRAINT [FK_REPRESENTANTE_ALUMNO]
    FOREIGN KEY ([ID_ALUMNO])
    REFERENCES [dbo].[ALUMNO]
        ([ID_ALUMNO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_REPRESENTANTE_ALUMNO'
CREATE INDEX [IX_FK_REPRESENTANTE_ALUMNO]
ON [dbo].[REPRESENTANTE]
    ([ID_ALUMNO]);
GO

-- Creating foreign key on [ID_REPRESENTANTE] in table 'ENTORNO_FAMILIAR'
ALTER TABLE [dbo].[ENTORNO_FAMILIAR]
ADD CONSTRAINT [FK_ENTORNO_FAMILIAR_REPRESENTANTE]
    FOREIGN KEY ([ID_REPRESENTANTE])
    REFERENCES [dbo].[REPRESENTANTE]
        ([ID_REPRESENTANTE])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ENTORNO_FAMILIAR_REPRESENTANTE'
CREATE INDEX [IX_FK_ENTORNO_FAMILIAR_REPRESENTANTE]
ON [dbo].[ENTORNO_FAMILIAR]
    ([ID_REPRESENTANTE]);
GO

-- Creating foreign key on [ID_CARGO] in table 'PERSONA'
ALTER TABLE [dbo].[PERSONA]
ADD CONSTRAINT [FK_PERSONA_CARGO]
    FOREIGN KEY ([ID_CARGO])
    REFERENCES [dbo].[CARGO]
        ([ID_CARGO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PERSONA_CARGO'
CREATE INDEX [IX_FK_PERSONA_CARGO]
ON [dbo].[PERSONA]
    ([ID_CARGO]);
GO

-- Creating foreign key on [ID_TELEFONO] in table 'PERSONA'
ALTER TABLE [dbo].[PERSONA]
ADD CONSTRAINT [FK_PERSONA_TELEFONO]
    FOREIGN KEY ([ID_TELEFONO])
    REFERENCES [dbo].[TELEFONO]
        ([ID_TELEFONO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PERSONA_TELEFONO'
CREATE INDEX [IX_FK_PERSONA_TELEFONO]
ON [dbo].[PERSONA]
    ([ID_TELEFONO]);
GO

-- Creating foreign key on [ID_PERSONA] in table 'REPRESENTANTE'
ALTER TABLE [dbo].[REPRESENTANTE]
ADD CONSTRAINT [FK_REPRESENTANTE_PERSONA]
    FOREIGN KEY ([ID_PERSONA])
    REFERENCES [dbo].[PERSONA]
        ([ID_PERSONA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_REPRESENTANTE_PERSONA'
CREATE INDEX [IX_FK_REPRESENTANTE_PERSONA]
ON [dbo].[REPRESENTANTE]
    ([ID_PERSONA]);
GO

-- Creating foreign key on [ID_PARENTESCO] in table 'REPRESENTANTE'
ALTER TABLE [dbo].[REPRESENTANTE]
ADD CONSTRAINT [FK_REPRESENTANTE_PARENTESCO]
    FOREIGN KEY ([ID_PARENTESCO])
    REFERENCES [dbo].[PARENTESCO]
        ([ID_PARENTESCO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_REPRESENTANTE_PARENTESCO'
CREATE INDEX [IX_FK_REPRESENTANTE_PARENTESCO]
ON [dbo].[REPRESENTANTE]
    ([ID_PARENTESCO]);
GO

-- Creating foreign key on [ID_MATRICULA] in table 'REPRESENTANTE_LEGAL'
ALTER TABLE [dbo].[REPRESENTANTE_LEGAL]
ADD CONSTRAINT [FK_REPRESENTANTE_LEGAL_MATRICULA]
    FOREIGN KEY ([ID_MATRICULA])
    REFERENCES [dbo].[MATRICULA]
        ([ID_MATRICULA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_REPRESENTANTE_LEGAL_MATRICULA'
CREATE INDEX [IX_FK_REPRESENTANTE_LEGAL_MATRICULA]
ON [dbo].[REPRESENTANTE_LEGAL]
    ([ID_MATRICULA]);
GO

-- Creating foreign key on [ID_TELEFONO] in table 'REPRESENTANTE_LEGAL'
ALTER TABLE [dbo].[REPRESENTANTE_LEGAL]
ADD CONSTRAINT [FK_REPRESENTANTE_LEGAL_TELEFONO]
    FOREIGN KEY ([ID_TELEFONO])
    REFERENCES [dbo].[TELEFONO]
        ([ID_TELEFONO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_REPRESENTANTE_LEGAL_TELEFONO'
CREATE INDEX [IX_FK_REPRESENTANTE_LEGAL_TELEFONO]
ON [dbo].[REPRESENTANTE_LEGAL]
    ([ID_TELEFONO]);
GO

-- Creating foreign key on [ID_AREAGEOPADRE] in table 'AREA_GEOGRAFICA'
ALTER TABLE [dbo].[AREA_GEOGRAFICA]
ADD CONSTRAINT [FK_AREA_GEOGRAFICA_AREA_GEOGRAFICA]
    FOREIGN KEY ([ID_AREAGEOPADRE])
    REFERENCES [dbo].[AREA_GEOGRAFICA]
        ([ID_AREAGEOGRAFICA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_AREA_GEOGRAFICA_AREA_GEOGRAFICA'
CREATE INDEX [IX_FK_AREA_GEOGRAFICA_AREA_GEOGRAFICA]
ON [dbo].[AREA_GEOGRAFICA]
    ([ID_AREAGEOPADRE]);
GO

-- Creating foreign key on [ID_CODIGO] in table 'AREA_GEOGRAFICA'
ALTER TABLE [dbo].[AREA_GEOGRAFICA]
ADD CONSTRAINT [FK_AREA_GEOGRAFICA_CODIGOS]
    FOREIGN KEY ([ID_CODIGO])
    REFERENCES [dbo].[CODIGOS]
        ([ID_CODIGO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_AREA_GEOGRAFICA_CODIGOS'
CREATE INDEX [IX_FK_AREA_GEOGRAFICA_CODIGOS]
ON [dbo].[AREA_GEOGRAFICA]
    ([ID_CODIGO]);
GO

-- Creating foreign key on [ID_CARGOPADRE] in table 'CARGO'
ALTER TABLE [dbo].[CARGO]
ADD CONSTRAINT [FK_CARGO_CARGO]
    FOREIGN KEY ([ID_CARGOPADRE])
    REFERENCES [dbo].[CARGO]
        ([ID_CARGO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CARGO_CARGO'
CREATE INDEX [IX_FK_CARGO_CARGO]
ON [dbo].[CARGO]
    ([ID_CARGOPADRE]);
GO

-- Creating foreign key on [ID_HORARIO] in table 'COLEGIATURA'
ALTER TABLE [dbo].[COLEGIATURA]
ADD CONSTRAINT [FK_COLEGIATURA_HORARIO]
    FOREIGN KEY ([ID_HORARIO])
    REFERENCES [dbo].[HORARIO]
        ([ID_HORARIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_COLEGIATURA_HORARIO'
CREATE INDEX [IX_FK_COLEGIATURA_HORARIO]
ON [dbo].[COLEGIATURA]
    ([ID_HORARIO]);
GO

-- Creating foreign key on [ID_HORARIO] in table 'MATRICULA'
ALTER TABLE [dbo].[MATRICULA]
ADD CONSTRAINT [FK_MATRICULA_HORARIO]
    FOREIGN KEY ([ID_HORARIO])
    REFERENCES [dbo].[HORARIO]
        ([ID_HORARIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_MATRICULA_HORARIO'
CREATE INDEX [IX_FK_MATRICULA_HORARIO]
ON [dbo].[MATRICULA]
    ([ID_HORARIO]);
GO

-- Creating foreign key on [ID_PERIODO] in table 'COLEGIATURA'
ALTER TABLE [dbo].[COLEGIATURA]
ADD CONSTRAINT [FK_COLEGIATURA_PERIODO]
    FOREIGN KEY ([ID_PERIODO])
    REFERENCES [dbo].[PERIODO]
        ([ID_PERIODO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_COLEGIATURA_PERIODO'
CREATE INDEX [IX_FK_COLEGIATURA_PERIODO]
ON [dbo].[COLEGIATURA]
    ([ID_PERIODO]);
GO

-- Creating foreign key on [ID_PERIODO] in table 'MATRICULA'
ALTER TABLE [dbo].[MATRICULA]
ADD CONSTRAINT [FK_MATRICULA_PERIODO]
    FOREIGN KEY ([ID_PERIODO])
    REFERENCES [dbo].[PERIODO]
        ([ID_PERIODO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_MATRICULA_PERIODO'
CREATE INDEX [IX_FK_MATRICULA_PERIODO]
ON [dbo].[MATRICULA]
    ([ID_PERIODO]);
GO

-- Creating foreign key on [ID_TELEFONO] in table 'REFERENCIA'
ALTER TABLE [dbo].[REFERENCIA]
ADD CONSTRAINT [FK_REFERENCIA_TELEFONO]
    FOREIGN KEY ([ID_TELEFONO])
    REFERENCES [dbo].[TELEFONO]
        ([ID_TELEFONO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_REFERENCIA_TELEFONO'
CREATE INDEX [IX_FK_REFERENCIA_TELEFONO]
ON [dbo].[REFERENCIA]
    ([ID_TELEFONO]);
GO

-- Creating foreign key on [ID_REQUISITO] in table 'REQUISITOS_MATRICULA'
ALTER TABLE [dbo].[REQUISITOS_MATRICULA]
ADD CONSTRAINT [FK_REQUISITOS_MATRICULA_REQUISITO]
    FOREIGN KEY ([ID_REQUISITO])
    REFERENCES [dbo].[REQUISITO]
        ([ID_REQUISITO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_REQUISITOS_MATRICULA_REQUISITO'
CREATE INDEX [IX_FK_REQUISITOS_MATRICULA_REQUISITO]
ON [dbo].[REQUISITOS_MATRICULA]
    ([ID_REQUISITO]);
GO

-- Creating foreign key on [ID_INSCRIPCION] in table 'MATRICULA'
ALTER TABLE [dbo].[MATRICULA]
ADD CONSTRAINT [FK_MATRICULA_INSCRIPCION]
    FOREIGN KEY ([ID_INSCRIPCION])
    REFERENCES [dbo].[INSCRIPCION]
        ([ID_INSCRIPCION])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_MATRICULA_INSCRIPCION'
CREATE INDEX [IX_FK_MATRICULA_INSCRIPCION]
ON [dbo].[MATRICULA]
    ([ID_INSCRIPCION]);
GO

-- Creating foreign key on [ID_MATRICULA] in table 'REQUISITOS_MATRICULA'
ALTER TABLE [dbo].[REQUISITOS_MATRICULA]
ADD CONSTRAINT [FK_REQUISITOS_MATRICULA_MATRICULA]
    FOREIGN KEY ([ID_MATRICULA])
    REFERENCES [dbo].[MATRICULA]
        ([ID_MATRICULA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_REQUISITOS_MATRICULA_MATRICULA'
CREATE INDEX [IX_FK_REQUISITOS_MATRICULA_MATRICULA]
ON [dbo].[REQUISITOS_MATRICULA]
    ([ID_MATRICULA]);
GO

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------