//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios en este archivo pueden ocasionar un comportamiento incorrecto y se perderán si
//     el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
using Capas.Dominio.Core.Entidades;

namespace Oporie.Dominio.ModuloPrincipal.Entidades
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(AREA_GEOGRAFICA))]
    public partial class CODIGOS: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Propiedades primitivas
    
        [DataMember]
        public string ID_CODIGO
        {
            get { return _iD_CODIGO; }
            set
            {
                if (_iD_CODIGO != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("La propiedad 'ID_CODIGO' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.");
                    }
                    _iD_CODIGO = value;
                    OnPropertyChanged("ID_CODIGO");
                }
            }
        }
        private string _iD_CODIGO;
    
        [DataMember]
        public string COD_DESCRIPCION
        {
            get { return _cOD_DESCRIPCION; }
            set
            {
                if (_cOD_DESCRIPCION != value)
                {
                    _cOD_DESCRIPCION = value;
                    OnPropertyChanged("COD_DESCRIPCION");
                }
            }
        }
        private string _cOD_DESCRIPCION;
    
        [DataMember]
        public bool COD_ESTADO
        {
            get { return _cOD_ESTADO; }
            set
            {
                if (_cOD_ESTADO != value)
                {
                    _cOD_ESTADO = value;
                    OnPropertyChanged("COD_ESTADO");
                }
            }
        }
        private bool _cOD_ESTADO;

        #endregion
        #region Propiedades de navegación
    
        [DataMember]
        public TrackableCollection<AREA_GEOGRAFICA> AREA_GEOGRAFICA
        {
            get
            {
                if (_aREA_GEOGRAFICA == null)
                {
                    _aREA_GEOGRAFICA = new TrackableCollection<AREA_GEOGRAFICA>();
                    _aREA_GEOGRAFICA.CollectionChanged += FixupAREA_GEOGRAFICA;
                }
                return _aREA_GEOGRAFICA;
            }
            set
            {
                if (!ReferenceEquals(_aREA_GEOGRAFICA, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("No se puede establecer el elemento FixupChangeTrackingCollection cuando se ha habilitado ChangeTracking");
                    }
                    if (_aREA_GEOGRAFICA != null)
                    {
                        _aREA_GEOGRAFICA.CollectionChanged -= FixupAREA_GEOGRAFICA;
                    }
                    _aREA_GEOGRAFICA = value;
                    if (_aREA_GEOGRAFICA != null)
                    {
                        _aREA_GEOGRAFICA.CollectionChanged += FixupAREA_GEOGRAFICA;
                    }
                    OnNavigationPropertyChanged("AREA_GEOGRAFICA");
                }
            }
        }
        private TrackableCollection<AREA_GEOGRAFICA> _aREA_GEOGRAFICA;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            AREA_GEOGRAFICA.Clear();
        }

        #endregion
        #region Corrección de asociación
    
        private void FixupAREA_GEOGRAFICA(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (AREA_GEOGRAFICA item in e.NewItems)
                {
                    item.CODIGOS = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("AREA_GEOGRAFICA", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (AREA_GEOGRAFICA item in e.OldItems)
                {
                    if (ReferenceEquals(item.CODIGOS, this))
                    {
                        item.CODIGOS = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("AREA_GEOGRAFICA", item);
                    }
                }
            }
        }

        #endregion
    }
}
