//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios en este archivo pueden ocasionar un comportamiento incorrecto y se perderán si
//     el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
using Capas.Dominio.Core.Entidades;

namespace Oporie.Dominio.ModuloPrincipal.Entidades
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(REPRESENTANTE))]
    public partial class PARENTESCO: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Propiedades primitivas
    
        [DataMember]
        public System.Guid ID_PARENTESCO
        {
            get { return _iD_PARENTESCO; }
            set
            {
                if (_iD_PARENTESCO != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("La propiedad 'ID_PARENTESCO' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.");
                    }
                    _iD_PARENTESCO = value;
                    OnPropertyChanged("ID_PARENTESCO");
                }
            }
        }
        private System.Guid _iD_PARENTESCO;
    
        [DataMember]
        public string PAR_DESCRIPCION
        {
            get { return _pAR_DESCRIPCION; }
            set
            {
                if (_pAR_DESCRIPCION != value)
                {
                    _pAR_DESCRIPCION = value;
                    OnPropertyChanged("PAR_DESCRIPCION");
                }
            }
        }
        private string _pAR_DESCRIPCION;
    
        [DataMember]
        public bool PAR_ESTADO
        {
            get { return _pAR_ESTADO; }
            set
            {
                if (_pAR_ESTADO != value)
                {
                    _pAR_ESTADO = value;
                    OnPropertyChanged("PAR_ESTADO");
                }
            }
        }
        private bool _pAR_ESTADO;

        #endregion
        #region Propiedades de navegación
    
        [DataMember]
        public TrackableCollection<REPRESENTANTE> REPRESENTANTE
        {
            get
            {
                if (_rEPRESENTANTE == null)
                {
                    _rEPRESENTANTE = new TrackableCollection<REPRESENTANTE>();
                    _rEPRESENTANTE.CollectionChanged += FixupREPRESENTANTE;
                }
                return _rEPRESENTANTE;
            }
            set
            {
                if (!ReferenceEquals(_rEPRESENTANTE, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("No se puede establecer el elemento FixupChangeTrackingCollection cuando se ha habilitado ChangeTracking");
                    }
                    if (_rEPRESENTANTE != null)
                    {
                        _rEPRESENTANTE.CollectionChanged -= FixupREPRESENTANTE;
                    }
                    _rEPRESENTANTE = value;
                    if (_rEPRESENTANTE != null)
                    {
                        _rEPRESENTANTE.CollectionChanged += FixupREPRESENTANTE;
                    }
                    OnNavigationPropertyChanged("REPRESENTANTE");
                }
            }
        }
        private TrackableCollection<REPRESENTANTE> _rEPRESENTANTE;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            REPRESENTANTE.Clear();
        }

        #endregion
        #region Corrección de asociación
    
        private void FixupREPRESENTANTE(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (REPRESENTANTE item in e.NewItems)
                {
                    item.PARENTESCO = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("REPRESENTANTE", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (REPRESENTANTE item in e.OldItems)
                {
                    if (ReferenceEquals(item.PARENTESCO, this))
                    {
                        item.PARENTESCO = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("REPRESENTANTE", item);
                    }
                }
            }
        }

        #endregion
    }
}
