//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios en este archivo pueden ocasionar un comportamiento incorrecto y se perderán si
//     el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
using Capas.Dominio.Core.Entidades;

namespace Oporie.Dominio.ModuloPrincipal.Entidades
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(TELEFONO))]
    public partial class REFERENCIA: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Propiedades primitivas
    
        [DataMember]
        public System.Guid ID_REFERENCIA
        {
            get { return _iD_REFERENCIA; }
            set
            {
                if (_iD_REFERENCIA != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("La propiedad 'ID_REFERENCIA' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.");
                    }
                    _iD_REFERENCIA = value;
                    OnPropertyChanged("ID_REFERENCIA");
                }
            }
        }
        private System.Guid _iD_REFERENCIA;
    
        [DataMember]
        public System.Guid ID_TELEFONO
        {
            get { return _iD_TELEFONO; }
            set
            {
                if (_iD_TELEFONO != value)
                {
                    ChangeTracker.RecordOriginalValue("ID_TELEFONO", _iD_TELEFONO);
                    if (!IsDeserializing)
                    {
                        if (TELEFONO != null && TELEFONO.ID_TELEFONO != value)
                        {
                            TELEFONO = null;
                        }
                    }
                    _iD_TELEFONO = value;
                    OnPropertyChanged("ID_TELEFONO");
                }
            }
        }
        private System.Guid _iD_TELEFONO;
    
        [DataMember]
        public string REF_CEDULA
        {
            get { return _rEF_CEDULA; }
            set
            {
                if (_rEF_CEDULA != value)
                {
                    _rEF_CEDULA = value;
                    OnPropertyChanged("REF_CEDULA");
                }
            }
        }
        private string _rEF_CEDULA;
    
        [DataMember]
        public string REF_FIRSTNAME
        {
            get { return _rEF_FIRSTNAME; }
            set
            {
                if (_rEF_FIRSTNAME != value)
                {
                    _rEF_FIRSTNAME = value;
                    OnPropertyChanged("REF_FIRSTNAME");
                }
            }
        }
        private string _rEF_FIRSTNAME;
    
        [DataMember]
        public string REF_LASTNAME
        {
            get { return _rEF_LASTNAME; }
            set
            {
                if (_rEF_LASTNAME != value)
                {
                    _rEF_LASTNAME = value;
                    OnPropertyChanged("REF_LASTNAME");
                }
            }
        }
        private string _rEF_LASTNAME;
    
        [DataMember]
        public string REF_DIRECCION
        {
            get { return _rEF_DIRECCION; }
            set
            {
                if (_rEF_DIRECCION != value)
                {
                    _rEF_DIRECCION = value;
                    OnPropertyChanged("REF_DIRECCION");
                }
            }
        }
        private string _rEF_DIRECCION;
    
        [DataMember]
        public bool REF_ESTADO
        {
            get { return _rEF_ESTADO; }
            set
            {
                if (_rEF_ESTADO != value)
                {
                    _rEF_ESTADO = value;
                    OnPropertyChanged("REF_ESTADO");
                }
            }
        }
        private bool _rEF_ESTADO;

        #endregion
        #region Propiedades de navegación
    
        [DataMember]
        public TELEFONO TELEFONO
        {
            get { return _tELEFONO; }
            set
            {
                if (!ReferenceEquals(_tELEFONO, value))
                {
                    var previousValue = _tELEFONO;
                    _tELEFONO = value;
                    FixupTELEFONO(previousValue);
                    OnNavigationPropertyChanged("TELEFONO");
                }
            }
        }
        private TELEFONO _tELEFONO;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            TELEFONO = null;
        }

        #endregion
        #region Corrección de asociación
    
        private void FixupTELEFONO(TELEFONO previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.REFERENCIA.Contains(this))
            {
                previousValue.REFERENCIA.Remove(this);
            }
    
            if (TELEFONO != null)
            {
                if (!TELEFONO.REFERENCIA.Contains(this))
                {
                    TELEFONO.REFERENCIA.Add(this);
                }
    
                ID_TELEFONO = TELEFONO.ID_TELEFONO;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("TELEFONO")
                    && (ChangeTracker.OriginalValues["TELEFONO"] == TELEFONO))
                {
                    ChangeTracker.OriginalValues.Remove("TELEFONO");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("TELEFONO", previousValue);
                }
                if (TELEFONO != null && !TELEFONO.ChangeTracker.ChangeTrackingEnabled)
                {
                    TELEFONO.StartTracking();
                }
            }
        }

        #endregion
    }
}
