//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios en este archivo pueden ocasionar un comportamiento incorrecto y se perderán si
//     el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
using Capas.Dominio.Core.Entidades;

namespace Oporie.Dominio.ModuloPrincipal.Entidades
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(ALUMNO))]
    [KnownType(typeof(ENTORNO_FAMILIAR))]
    [KnownType(typeof(PERSONA))]
    [KnownType(typeof(PARENTESCO))]
    public partial class REPRESENTANTE: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Propiedades primitivas
    
        [DataMember]
        public System.Guid ID_REPRESENTANTE
        {
            get { return _iD_REPRESENTANTE; }
            set
            {
                if (_iD_REPRESENTANTE != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("La propiedad 'ID_REPRESENTANTE' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.");
                    }
                    _iD_REPRESENTANTE = value;
                    OnPropertyChanged("ID_REPRESENTANTE");
                }
            }
        }
        private System.Guid _iD_REPRESENTANTE;
    
        [DataMember]
        public System.Guid ID_PARENTESCO
        {
            get { return _iD_PARENTESCO; }
            set
            {
                if (_iD_PARENTESCO != value)
                {
                    ChangeTracker.RecordOriginalValue("ID_PARENTESCO", _iD_PARENTESCO);
                    if (!IsDeserializing)
                    {
                        if (PARENTESCO != null && PARENTESCO.ID_PARENTESCO != value)
                        {
                            PARENTESCO = null;
                        }
                    }
                    _iD_PARENTESCO = value;
                    OnPropertyChanged("ID_PARENTESCO");
                }
            }
        }
        private System.Guid _iD_PARENTESCO;
    
        [DataMember]
        public System.Guid ID_PERSONA
        {
            get { return _iD_PERSONA; }
            set
            {
                if (_iD_PERSONA != value)
                {
                    ChangeTracker.RecordOriginalValue("ID_PERSONA", _iD_PERSONA);
                    if (!IsDeserializing)
                    {
                        if (PERSONA != null && PERSONA.ID_PERSONA != value)
                        {
                            PERSONA = null;
                        }
                    }
                    _iD_PERSONA = value;
                    OnPropertyChanged("ID_PERSONA");
                }
            }
        }
        private System.Guid _iD_PERSONA;
    
        [DataMember]
        public System.Guid ID_ALUMNO
        {
            get { return _iD_ALUMNO; }
            set
            {
                if (_iD_ALUMNO != value)
                {
                    ChangeTracker.RecordOriginalValue("ID_ALUMNO", _iD_ALUMNO);
                    if (!IsDeserializing)
                    {
                        if (ALUMNO != null && ALUMNO.ID_ALUMNO != value)
                        {
                            ALUMNO = null;
                        }
                    }
                    _iD_ALUMNO = value;
                    OnPropertyChanged("ID_ALUMNO");
                }
            }
        }
        private System.Guid _iD_ALUMNO;
    
        [DataMember]
        public Nullable<System.DateTime> REP_FECHAINGRESO
        {
            get { return _rEP_FECHAINGRESO; }
            set
            {
                if (_rEP_FECHAINGRESO != value)
                {
                    _rEP_FECHAINGRESO = value;
                    OnPropertyChanged("REP_FECHAINGRESO");
                }
            }
        }
        private Nullable<System.DateTime> _rEP_FECHAINGRESO;
    
        [DataMember]
        public bool REP_ESTADO
        {
            get { return _rEP_ESTADO; }
            set
            {
                if (_rEP_ESTADO != value)
                {
                    _rEP_ESTADO = value;
                    OnPropertyChanged("REP_ESTADO");
                }
            }
        }
        private bool _rEP_ESTADO;

        #endregion
        #region Propiedades de navegación
    
        [DataMember]
        public ALUMNO ALUMNO
        {
            get { return _aLUMNO; }
            set
            {
                if (!ReferenceEquals(_aLUMNO, value))
                {
                    var previousValue = _aLUMNO;
                    _aLUMNO = value;
                    FixupALUMNO(previousValue);
                    OnNavigationPropertyChanged("ALUMNO");
                }
            }
        }
        private ALUMNO _aLUMNO;
    
        [DataMember]
        public TrackableCollection<ENTORNO_FAMILIAR> ENTORNO_FAMILIAR
        {
            get
            {
                if (_eNTORNO_FAMILIAR == null)
                {
                    _eNTORNO_FAMILIAR = new TrackableCollection<ENTORNO_FAMILIAR>();
                    _eNTORNO_FAMILIAR.CollectionChanged += FixupENTORNO_FAMILIAR;
                }
                return _eNTORNO_FAMILIAR;
            }
            set
            {
                if (!ReferenceEquals(_eNTORNO_FAMILIAR, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("No se puede establecer el elemento FixupChangeTrackingCollection cuando se ha habilitado ChangeTracking");
                    }
                    if (_eNTORNO_FAMILIAR != null)
                    {
                        _eNTORNO_FAMILIAR.CollectionChanged -= FixupENTORNO_FAMILIAR;
                    }
                    _eNTORNO_FAMILIAR = value;
                    if (_eNTORNO_FAMILIAR != null)
                    {
                        _eNTORNO_FAMILIAR.CollectionChanged += FixupENTORNO_FAMILIAR;
                    }
                    OnNavigationPropertyChanged("ENTORNO_FAMILIAR");
                }
            }
        }
        private TrackableCollection<ENTORNO_FAMILIAR> _eNTORNO_FAMILIAR;
    
        [DataMember]
        public PERSONA PERSONA
        {
            get { return _pERSONA; }
            set
            {
                if (!ReferenceEquals(_pERSONA, value))
                {
                    var previousValue = _pERSONA;
                    _pERSONA = value;
                    FixupPERSONA(previousValue);
                    OnNavigationPropertyChanged("PERSONA");
                }
            }
        }
        private PERSONA _pERSONA;
    
        [DataMember]
        public PARENTESCO PARENTESCO
        {
            get { return _pARENTESCO; }
            set
            {
                if (!ReferenceEquals(_pARENTESCO, value))
                {
                    var previousValue = _pARENTESCO;
                    _pARENTESCO = value;
                    FixupPARENTESCO(previousValue);
                    OnNavigationPropertyChanged("PARENTESCO");
                }
            }
        }
        private PARENTESCO _pARENTESCO;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            ALUMNO = null;
            ENTORNO_FAMILIAR.Clear();
            PERSONA = null;
            PARENTESCO = null;
        }

        #endregion
        #region Corrección de asociación
    
        private void FixupALUMNO(ALUMNO previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.REPRESENTANTE.Contains(this))
            {
                previousValue.REPRESENTANTE.Remove(this);
            }
    
            if (ALUMNO != null)
            {
                if (!ALUMNO.REPRESENTANTE.Contains(this))
                {
                    ALUMNO.REPRESENTANTE.Add(this);
                }
    
                ID_ALUMNO = ALUMNO.ID_ALUMNO;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("ALUMNO")
                    && (ChangeTracker.OriginalValues["ALUMNO"] == ALUMNO))
                {
                    ChangeTracker.OriginalValues.Remove("ALUMNO");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("ALUMNO", previousValue);
                }
                if (ALUMNO != null && !ALUMNO.ChangeTracker.ChangeTrackingEnabled)
                {
                    ALUMNO.StartTracking();
                }
            }
        }
    
        private void FixupPERSONA(PERSONA previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.REPRESENTANTE.Contains(this))
            {
                previousValue.REPRESENTANTE.Remove(this);
            }
    
            if (PERSONA != null)
            {
                if (!PERSONA.REPRESENTANTE.Contains(this))
                {
                    PERSONA.REPRESENTANTE.Add(this);
                }
    
                ID_PERSONA = PERSONA.ID_PERSONA;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("PERSONA")
                    && (ChangeTracker.OriginalValues["PERSONA"] == PERSONA))
                {
                    ChangeTracker.OriginalValues.Remove("PERSONA");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("PERSONA", previousValue);
                }
                if (PERSONA != null && !PERSONA.ChangeTracker.ChangeTrackingEnabled)
                {
                    PERSONA.StartTracking();
                }
            }
        }
    
        private void FixupPARENTESCO(PARENTESCO previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.REPRESENTANTE.Contains(this))
            {
                previousValue.REPRESENTANTE.Remove(this);
            }
    
            if (PARENTESCO != null)
            {
                if (!PARENTESCO.REPRESENTANTE.Contains(this))
                {
                    PARENTESCO.REPRESENTANTE.Add(this);
                }
    
                ID_PARENTESCO = PARENTESCO.ID_PARENTESCO;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("PARENTESCO")
                    && (ChangeTracker.OriginalValues["PARENTESCO"] == PARENTESCO))
                {
                    ChangeTracker.OriginalValues.Remove("PARENTESCO");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("PARENTESCO", previousValue);
                }
                if (PARENTESCO != null && !PARENTESCO.ChangeTracker.ChangeTrackingEnabled)
                {
                    PARENTESCO.StartTracking();
                }
            }
        }
    
        private void FixupENTORNO_FAMILIAR(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (ENTORNO_FAMILIAR item in e.NewItems)
                {
                    item.REPRESENTANTE = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("ENTORNO_FAMILIAR", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ENTORNO_FAMILIAR item in e.OldItems)
                {
                    if (ReferenceEquals(item.REPRESENTANTE, this))
                    {
                        item.REPRESENTANTE = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("ENTORNO_FAMILIAR", item);
                    }
                }
            }
        }

        #endregion
    }
}
