//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios en este archivo pueden ocasionar un comportamiento incorrecto y se perderán si
//     el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
using Capas.Dominio.Core.Entidades;

namespace Oporie.Dominio.ModuloPrincipal.Entidades
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(REQUISITOS_MATRICULA))]
    public partial class REQUISITO: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Propiedades primitivas
    
        [DataMember]
        public System.Guid ID_REQUISITO
        {
            get { return _iD_REQUISITO; }
            set
            {
                if (_iD_REQUISITO != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("La propiedad 'ID_REQUISITO' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.");
                    }
                    _iD_REQUISITO = value;
                    OnPropertyChanged("ID_REQUISITO");
                }
            }
        }
        private System.Guid _iD_REQUISITO;
    
        [DataMember]
        public string REQ_DESCRIPCION
        {
            get { return _rEQ_DESCRIPCION; }
            set
            {
                if (_rEQ_DESCRIPCION != value)
                {
                    _rEQ_DESCRIPCION = value;
                    OnPropertyChanged("REQ_DESCRIPCION");
                }
            }
        }
        private string _rEQ_DESCRIPCION;
    
        [DataMember]
        public bool REQ_ESTADO
        {
            get { return _rEQ_ESTADO; }
            set
            {
                if (_rEQ_ESTADO != value)
                {
                    _rEQ_ESTADO = value;
                    OnPropertyChanged("REQ_ESTADO");
                }
            }
        }
        private bool _rEQ_ESTADO;

        #endregion
        #region Propiedades de navegación
    
        [DataMember]
        public TrackableCollection<REQUISITOS_MATRICULA> REQUISITOS_MATRICULA
        {
            get
            {
                if (_rEQUISITOS_MATRICULA == null)
                {
                    _rEQUISITOS_MATRICULA = new TrackableCollection<REQUISITOS_MATRICULA>();
                    _rEQUISITOS_MATRICULA.CollectionChanged += FixupREQUISITOS_MATRICULA;
                }
                return _rEQUISITOS_MATRICULA;
            }
            set
            {
                if (!ReferenceEquals(_rEQUISITOS_MATRICULA, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("No se puede establecer el elemento FixupChangeTrackingCollection cuando se ha habilitado ChangeTracking");
                    }
                    if (_rEQUISITOS_MATRICULA != null)
                    {
                        _rEQUISITOS_MATRICULA.CollectionChanged -= FixupREQUISITOS_MATRICULA;
                    }
                    _rEQUISITOS_MATRICULA = value;
                    if (_rEQUISITOS_MATRICULA != null)
                    {
                        _rEQUISITOS_MATRICULA.CollectionChanged += FixupREQUISITOS_MATRICULA;
                    }
                    OnNavigationPropertyChanged("REQUISITOS_MATRICULA");
                }
            }
        }
        private TrackableCollection<REQUISITOS_MATRICULA> _rEQUISITOS_MATRICULA;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            REQUISITOS_MATRICULA.Clear();
        }

        #endregion
        #region Corrección de asociación
    
        private void FixupREQUISITOS_MATRICULA(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (REQUISITOS_MATRICULA item in e.NewItems)
                {
                    item.REQUISITO = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("REQUISITOS_MATRICULA", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (REQUISITOS_MATRICULA item in e.OldItems)
                {
                    if (ReferenceEquals(item.REQUISITO, this))
                    {
                        item.REQUISITO = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("REQUISITOS_MATRICULA", item);
                    }
                }
            }
        }

        #endregion
    }
}
