//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios en este archivo pueden ocasionar un comportamiento incorrecto y se perderán si
//     el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
using Capas.Dominio.Core.Entidades;

namespace Oporie.Dominio.ModuloPrincipal.Entidades
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(REQUISITO))]
    [KnownType(typeof(MATRICULA))]
    public partial class REQUISITOS_MATRICULA: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Propiedades primitivas
    
        [DataMember]
        public System.Guid ID_REQUISITOMATRICULA
        {
            get { return _iD_REQUISITOMATRICULA; }
            set
            {
                if (_iD_REQUISITOMATRICULA != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("La propiedad 'ID_REQUISITOMATRICULA' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.");
                    }
                    _iD_REQUISITOMATRICULA = value;
                    OnPropertyChanged("ID_REQUISITOMATRICULA");
                }
            }
        }
        private System.Guid _iD_REQUISITOMATRICULA;
    
        [DataMember]
        public System.Guid ID_REQUISITO
        {
            get { return _iD_REQUISITO; }
            set
            {
                if (_iD_REQUISITO != value)
                {
                    ChangeTracker.RecordOriginalValue("ID_REQUISITO", _iD_REQUISITO);
                    if (!IsDeserializing)
                    {
                        if (REQUISITO != null && REQUISITO.ID_REQUISITO != value)
                        {
                            REQUISITO = null;
                        }
                    }
                    _iD_REQUISITO = value;
                    OnPropertyChanged("ID_REQUISITO");
                }
            }
        }
        private System.Guid _iD_REQUISITO;
    
        [DataMember]
        public System.Guid ID_MATRICULA
        {
            get { return _iD_MATRICULA; }
            set
            {
                if (_iD_MATRICULA != value)
                {
                    ChangeTracker.RecordOriginalValue("ID_MATRICULA", _iD_MATRICULA);
                    if (!IsDeserializing)
                    {
                        if (MATRICULA != null && MATRICULA.ID_MATRICULA != value)
                        {
                            MATRICULA = null;
                        }
                    }
                    _iD_MATRICULA = value;
                    OnPropertyChanged("ID_MATRICULA");
                }
            }
        }
        private System.Guid _iD_MATRICULA;
    
        [DataMember]
        public bool RMA_ESTADO
        {
            get { return _rMA_ESTADO; }
            set
            {
                if (_rMA_ESTADO != value)
                {
                    _rMA_ESTADO = value;
                    OnPropertyChanged("RMA_ESTADO");
                }
            }
        }
        private bool _rMA_ESTADO;

        #endregion
        #region Propiedades de navegación
    
        [DataMember]
        public REQUISITO REQUISITO
        {
            get { return _rEQUISITO; }
            set
            {
                if (!ReferenceEquals(_rEQUISITO, value))
                {
                    var previousValue = _rEQUISITO;
                    _rEQUISITO = value;
                    FixupREQUISITO(previousValue);
                    OnNavigationPropertyChanged("REQUISITO");
                }
            }
        }
        private REQUISITO _rEQUISITO;
    
        [DataMember]
        public MATRICULA MATRICULA
        {
            get { return _mATRICULA; }
            set
            {
                if (!ReferenceEquals(_mATRICULA, value))
                {
                    var previousValue = _mATRICULA;
                    _mATRICULA = value;
                    FixupMATRICULA(previousValue);
                    OnNavigationPropertyChanged("MATRICULA");
                }
            }
        }
        private MATRICULA _mATRICULA;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            REQUISITO = null;
            MATRICULA = null;
        }

        #endregion
        #region Corrección de asociación
    
        private void FixupREQUISITO(REQUISITO previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.REQUISITOS_MATRICULA.Contains(this))
            {
                previousValue.REQUISITOS_MATRICULA.Remove(this);
            }
    
            if (REQUISITO != null)
            {
                if (!REQUISITO.REQUISITOS_MATRICULA.Contains(this))
                {
                    REQUISITO.REQUISITOS_MATRICULA.Add(this);
                }
    
                ID_REQUISITO = REQUISITO.ID_REQUISITO;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("REQUISITO")
                    && (ChangeTracker.OriginalValues["REQUISITO"] == REQUISITO))
                {
                    ChangeTracker.OriginalValues.Remove("REQUISITO");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("REQUISITO", previousValue);
                }
                if (REQUISITO != null && !REQUISITO.ChangeTracker.ChangeTrackingEnabled)
                {
                    REQUISITO.StartTracking();
                }
            }
        }
    
        private void FixupMATRICULA(MATRICULA previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.REQUISITOS_MATRICULA.Contains(this))
            {
                previousValue.REQUISITOS_MATRICULA.Remove(this);
            }
    
            if (MATRICULA != null)
            {
                if (!MATRICULA.REQUISITOS_MATRICULA.Contains(this))
                {
                    MATRICULA.REQUISITOS_MATRICULA.Add(this);
                }
    
                ID_MATRICULA = MATRICULA.ID_MATRICULA;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("MATRICULA")
                    && (ChangeTracker.OriginalValues["MATRICULA"] == MATRICULA))
                {
                    ChangeTracker.OriginalValues.Remove("MATRICULA");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("MATRICULA", previousValue);
                }
                if (MATRICULA != null && !MATRICULA.ChangeTracker.ChangeTrackingEnabled)
                {
                    MATRICULA.StartTracking();
                }
            }
        }

        #endregion
    }
}
